"""empty message

Revision ID: 1807e368887b
Revises: 09e87a95f635
Create Date: 2018-09-02 17:01:14.849751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1807e368887b'
down_revision = '09e87a95f635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_of_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin', sa.Column('firstName', sa.String(length=50), nullable=False))
    op.add_column('admin', sa.Column('lastName', sa.String(length=50), nullable=False))
    op.add_column('organization', sa.Column('course', sa.String(length=50), nullable=False))
    op.add_column('professor', sa.Column('firstName', sa.String(length=50), nullable=False))
    op.add_column('professor', sa.Column('lastName', sa.String(length=50), nullable=False))
    op.drop_column('professor', 'name')
    op.add_column('reservation', sa.Column('reference', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'reference')
    op.add_column('professor', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('professor', 'lastName')
    op.drop_column('professor', 'firstName')
    op.drop_column('organization', 'course')
    op.drop_column('admin', 'lastName')
    op.drop_column('admin', 'firstName')
    op.drop_table('section')
    op.drop_table('field_of_study')
    # ### end Alembic commands ###
